
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Puzzle, ArrowRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export default function LogicPuzzlesLandingPage() {
  return (
    <main className="flex flex-1 flex-col items-center justify-center gap-6 p-4 lg:p-6">
      <div className="max-w-2xl w-full">
        <Card className="overflow-hidden">
             <CardHeader className="p-0">
                 <Image src="https://placehold.co/600x300.png" alt="Logic Puzzle" width={600} height={300} className="w-full" data-ai-hint="brain maze puzzle" />
            </CardHeader>
            <div className="p-6">
                <CardTitle className="flex items-center gap-3 text-3xl mb-2">
                    <Puzzle className="h-8 w-8 text-primary"/>
                    Logic Puzzles
                </CardTitle>
                <CardDescription className="text-lg mb-6">
                    Challenge your mind with a variety of logic puzzles. Read the scenario, analyze the constraints, and deduce the solution.
                </CardDescription>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-muted-foreground">
                    <div>
                        <h3 className="font-semibold text-foreground mb-2">How to Play:</h3>
                        <ul className="list-disc list-inside space-y-1">
                            <li>An AI will generate a unique logic puzzle for you.</li>
                            <li>Read the puzzle description carefully.</li>
                            <li>Use your reasoning skills to solve it.</li>
                            <li>Submit your answer to see if you are correct!</li>
                        </ul>
                    </div>
                     <div>
                        <h3 className="font-semibold text-foreground mb-2">Features:</h3>
                        <ul className="list-disc list-inside space-y-1">
                            <li>Endless puzzles generated by AI.</li>
                             <li>Various difficulty levels.</li>
                            <li>A great way to sharpen your critical thinking.</li>
                        </ul>
                    </div>
                </div>
                 <div className="mt-8">
                    <Link href="/games/logic-puzzles/play">
                        <Button className="w-full text-lg py-6">
                            Start Playing <ArrowRight className="ml-2"/>
                        </Button>
                    </Link>
                </div>
            </div>
        </Card>
      </div>
    </main>
  );
}
